### ISSUE TITLE
Nested coroutines. Is it possible?

### ISSUE THREAD

**Issue by facontidavide** [tonbit/coroutine#7]
Hi, I have a code that semantically is similar to this:

```c++
void routine()
{
    std::cout << "Hello" << std::endl;
    coroutine::yield();
    std::cout << "done" << std::endl;
}

void routine_nested()
{
    coroutine::routine_t rt = coroutine::create(routine);
    coroutine::resume(rt);
    coroutine::resume(rt);
    coroutine::yield();
}

int main()
{
    coroutine::routine_t nested_rt = coroutine::create(routine_nested);
    coroutine::resume(nested_rt);
    return 0;
}
```

Is it (at least conceptually, possible to make this work? This assertion currently fails:

```c++
inline int resume(routine_t id)
{
    assert(ordinator.current == 0);
```

**Comment by tonbit** [comment]
When routine() is finished, should the context be swapped back to routine_nested() or main() ?

**Comment by facontidavide** [comment]
Rather then ansering directly this question, I can tell you what is the overall behavior that I expect and that I actually get from other implementations like __libco__


```c++
void routine()
{
    std::cout << "Alpha" << std::endl;
    coroutine::yield();
    std::cout << "Beta" << std::endl;
}

void routine_nested()
{
    std::cout << "1" << std::endl;
    coroutine::yield();

    coroutine::routine_t child_rt = coroutine::create(routine);
    coroutine::resume(child_rt );
    coroutine::resume(child_rt );

    std::cout << "2" << std::endl;
   coroutine::yield();

    std::cout << "3" << std::endl;
}

int main()
{
    coroutine::routine_t nested_rt = coroutine::create(routine_nested);
    coroutine::resume(nested_rt);
    coroutine::resume(nested_rt);
    coroutine::resume(nested_rt);
    return 0;
}

/* Output

1
Alpha
Beta
2
3
*/
```

**Comment by tonbit** [comment]
I think it's possible but difficult to support different OS and lib.

**Comment by facontidavide** [comment]
I see. Unfortunately I do need this feature. I guess I need to switch to another library.

Nevertheless, great work, and thanks for making it available on Github.

Cheers

**Comment by Skycoder42** [comment]
Not directly a solution, but a hint in case you want to implement it yourself.

I transformed this library to be used with the Qt Framwork in https://github.com/Skycoder42/QtCoroutines. There, I implemented a way to use recursive coroutines using a stack-like container (See [qtcoroutine_p.h#L32](https://github.com/Skycoder42/QtCoroutines/blob/master/qtcoroutine_p.h#L32)). Might be useful for you.

**Comment by facontidavide** [comment]
Thanks, but I am already using libco, that seems to work exactly as I need
